/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*VungleSDKRegister_t)(VungleSDKCallback cbid, s3eCallback fn, void* userData);
typedef  s3eResult(*VungleSDKUnRegister_t)(VungleSDKCallback cbid, s3eCallback fn);
typedef  s3eResult(*VungleInit_t)(const char* androidAppId, const char* iOSAppId, const char* windowsAppId);
typedef  s3eResult(*VunglePlayAd_t)();
typedef  s3eResult(*VunglePlayAdWithOptions_t)(struct VungleSDKPlayOption* options);
typedef       bool(*VungleIsAdPlayable_t)();

/**
 * struct that gets filled in by VungleSDKRegister
 */
typedef struct VungleSDKFuncs
{
    VungleSDKRegister_t m_VungleSDKRegister;
    VungleSDKUnRegister_t m_VungleSDKUnRegister;
    VungleInit_t m_VungleInit;
    VunglePlayAd_t m_VunglePlayAd;
    VunglePlayAdWithOptions_t m_VunglePlayAdWithOptions;
    VungleIsAdPlayable_t m_VungleIsAdPlayable;
} VungleSDKFuncs;
